Add IC, DOB, Ward and AdmissionDate for Person class
AY2324S2-CS2103T-F10-1/tp pull request #30
Opened 2024-03-15 08:41 UTC by iamtr

**1. This will add parsing support for IC, DOB, Ward and AdmissionDate for the Person class.**

IC will take in the Singaporean NRIC/FIN format.
DOB is a date with DD/MM/YYYY format. 
Ward is a string. No restrictions.
AdmissionDate is a date with DD/MM/YYYY format.

**All 4 classes have the value contained inside stored as a String**
Person class has implemented all 4 classes.

**2. Support for parsing the new parameters are also implemented**

**3. Modified some test cases (not all!) to conform with the new parameters**
Test cases that failed are being commented out for now due to time constraints. **They need to be reimplemented**

Please let me know if anything needs to be changed

2024-03-15 09:48 UTC, ryanlimdx reviewed
LGTM! We could probably also remove the other unnecessary params like Email, Phone and Address in future updates

2024-03-15 09:48 UTC, ryanlimdx commented on src/main/java/seedu/address/logic/parser/ParserUtil.java
> +        if (!Dob.isValidDob(trimmedDob)) {
Perhaps we could use java's DateTime class for this.

2024-03-17 08:46 UTC, swtan346 requested changes
LGTM other than the Ic type

2024-03-17 08:46 UTC, swtan346 commented on src/main/java/seedu/address/model/person/Ic.java
> +public class Ic {
Should IC take in alphanumeric values instead of just an integer?

2024-03-18 07:20 UTC, iamtr commented
Hi all, for now I have decided to keep dob as a string, due to FXML issues. All values of dob, ic etc. will be renamed as "value" instead of "dob", "ic", as this is also how it is used for the fxml. For now, let's just leave it at that and change it in the future.

For the recent few commits, I also updated the UI, which means now the people's dob, ic, ward and others are displayed too. Please take a look and lmk if anything!

2024-03-18 08:57 UTC, swtan346 approved these changes

2024-03-18 08:59 UTC, merged